Repository forkyid/testing, pull requests merged in 2021-04, with the labels that each got.

#2 tambahIndex
  index.html
Labels: Development

#3 [GS-1] TambahIndex
  index.html
Labels: Staging

#5 [GS-1] Update Fitur
  123.py
Labels: Development

#6 [GS-1] Update Fitur
  123.py
Labels: Staging

#4 [GS-1] tambahIndex
  index.html
Labels: Production
